# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import forumlist.models


class Migration(migrations.Migration):

    dependencies = [
        ('forumlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(upload_to=forumlist.models.user_directory_path),
        ),
    ]
