# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumlist', '0003_post_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='data',
        ),
    ]
