# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import forumlist.models


class Migration(migrations.Migration):

    dependencies = [
        ('forumlist', '0006_remove_post_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(blank=True, upload_to=forumlist.models.user_directory_path),
        ),
    ]
