# Generated by Django 2.0 on 2017-12-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumlist', '0016_auto_20171207_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user_ids',
        ),
    ]
