# Generated by Django 2.0 on 2017-12-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumlist', '0017_auto_20171218_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_ids',
            new_name='user_id',
        ),
    ]
