# Generated by Django 2.0 on 2017-12-18 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forumlist', '0018_auto_20171218_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_caption2',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
