# Generated by Django 2.0 on 2017-12-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumlist', '0019_post_post_caption2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_caption2',
        ),
    ]
