# Generated by Django 2.0 on 2017-12-16 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reply.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forumlist', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_content', models.TextField(max_length=250)),
                ('reply_image', models.FileField(blank=True, upload_to=reply.models.user_directory_path)),
                ('reply_date', models.DateTimeField(auto_now_add=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_id', to='forumlist.Post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
